<?php
// Get Last 3 posts
$posts = Mage::getModel('blog/blog')
    ->getCollection()
    ->addPresentFilter()
    ->addFieldToFilter('status', 1)
    ->setOrder('created_time ', 'desc')
    ->setPageSize(3);


if ($posts) : ?>
    <section>
        <h1 class="title h1 articlesh1">Derniers Articles du Journal</h1>
        <ul class="articles">
            <?php foreach ($posts as $post):
                $post = Mage::getModel('blog/post')->load($post->getId());
                $cat = Mage::getModel('catalog/category')->load($post->getCatId()[0]);
                $cat = $cat->getName(); ?>
                <li class="article">
                    <article>
                        <div class="imgDiscover">
                            <?php if ($post->getFeaturedImage()): ?>
                                <img src="<?= Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$post->getFeaturedImage() ?>"
                                     alt="">
                            <?php endif; ?>
                            <div class="imgHover">
                                <a class="button btn" href="<?= $this->getBaseUrl().'blog/'.$post->getIdentifier() ?>"
                                   title="Discover">
                                    Découvrir
                                </a>
                            </div>
                        </div>
                        <div>
                            <a href="<?= $this->getBaseUrl().'blog/'.$post->getIdentifier(); ?>">
                                <h2 class="title subtitle"><?php echo $post->getTitle(); ?></h2></a>
                            <h3 class="article__cat"><?= $cat ?></h3>
                                <?= $post->getShortContent() ?>
                        </div>
                    </article>
                </li>
            <?php endforeach; ?>
        </ul>
    </section>
<?php endif; ?>