<div class="home-wrapper">
    <section class="landing-section">

        <div class="block-text">
            <h2 class="title-1">
                Dernière collection
            </h2>
            <p class="text-1">
                L'art de la fabrication française
            </p>
            <a class="button btn" href="javascript:;" title="Discover">
        <span>
          Découvrir
        </span>
            </a>
        </div>

    </section>
    <section class="collection-section">

        <div class="block-wrapper">
            <div class="block-left">

                <h2 class="title-2">
                    Nouveautés
                </h2>

                <div class="block-hover">
                    <div class="block-text">
                        <h2 class="title-1">
                            Nouveautés
                        </h2>
                        <p class="text-1">
                            L'art de la fabrication française
                        </p>
                        <a class="button" href="javascript:;" title="Discover">
              <span>
                Découvrir
              </span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="block-right">

                <h2 class="title-2">
                    Collection <br>
                    Vivienne
                </h2>

                <div class="block-hover">
                    <div class="block-text">
                        <h2 class="title-1">
                            Collection <br>
                            Vivienne
                        </h2>
                        <p class="text-1">
                            L'art de la fabrication française
                        </p>
                        <a class="button" href="javascript:;" title="Discover">
              <span>
                Découvrir
              </span>
                        </a>
                    </div>
                </div>
            </div>
        </div>

    </section>
</div>
