<?php
$_helper = Mage::helper('catalog/category');
$_categories = $_helper->getStoreCategories();
$last_categories = [];
foreach ($_categories as $_category) {
    if (count($last_categories) >= 3) {
        return;
    }
    $_category = Mage::getModel('catalog/category')->load($_category->getId());
    $last_categories[] = [
        "id" => $_category->getId(),
        "name" => $_category->getName(),
        "imgUrl" => $_category->getImageUrl(),
        "url" => $_category->getUrl(),
    ];
}
?>
<div class="home-wrapper">
    <section class="landing-section"
             style="background-image: url(<?= $last_categories[0]['imgUrl'] ?>)">

        <div class="block-text">
            <h2 class="title-1">
                Dernière collection
            </h2>
            <p class="text-1">
                L'art de la fabrication française
            </p>
            <a class="button btn" href="<?= $last_categories[0]['url'] ?>" title="Discover">
        <span>
          Découvrir
        </span>
            </a>
        </div>

    </section>
    <section class="collection-section">

        <div class="block-wrapper">
            <div class="block-left" style="background-image: url(<?= $last_categories[1]['imgUrl'] ?>)">

                <h2 class="title-2">
                    Collection <br>
                    <?= $last_categories[1]['name'] ?>
                </h2>

                <div class="block-hover">
                    <div class="block-text">
                        <h2 class="title-1">
                            Collection <br>
                            <?= $last_categories[1]['name'] ?>
                        </h2>
                        <p class="text-1">
                            L'art de la fabrication française
                        </p>
                        <a class="button btn" href="<?= $last_categories[1]['url'] ?>" title="Discover">
              <span>
                Découvrir
              </span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="block-right" style="background-image: url(<?= $last_categories[2]['imgUrl'] ?>)">>

                <h2 class="title-2">
                    Collection <br>
                    <?= $last_categories[2]['name'] ?>
                </h2>

                <div class="block-hover">
                    <div class="block-text">
                        <h2 class="title-1">
                            Collection <br>
                            <?= $last_categories[2]['name'] ?>
                        </h2>
                        <p class="text-1">
                            L'art de la fabrication française
                        </p>
                        <a class="button btn" href="<?= $last_categories[2]['url'] ?>" title="Discover">
                            <span>
                                Découvrir
                            </span>
                        </a>
                    </div>
                </div>
            </div>
        </div>

    </section>
</div>
