<?php $posts = $this->getPosts(); ?>

<section class="blog">
    <?php
    // Get Last 3 posts
    $posts = Mage::getModel('blog/blog')
        ->getCollection()
        ->addPresentFilter()
        ->addFieldToFilter('status', 1)
        ->setOrder('created_time ', 'desc')
        ->setPageSize(1);

    $post = $posts->getFirstItem();
    ?>
    <div class="blog__child"
         style="background-image: url(http://source.unsplash.com/random/)">
        <h2 class="blog__title title title--white">Hoop Earrings A Style From History</h2>
        <div class="content">
            <h3 class="author">de Claudia carvalho</h3>
            <span class="blog__date">
                <?= Mage::app()->getLocale()->date($post->getCreatedTime(), 'Y-M-d')->toString('d MMMM Y'); ?>
            </span>
        </div>
    </div>
    <div class="blog__child">
        <ul class="blog__list">
            <?php
            $posts = Mage::getModel('blog/blog')
                ->getCollection()
                ->addPresentFilter()
                ->addFieldToFilter('status', 1)
                ->setOrder('created_time ', 'desc');
            foreach ($posts as $post):
                ?>
                <li class="blog__item">
                    <div class="blog__item__img">
                        <a href="<?= $this->getBaseUrl().'blog/'.$post->getIdentifier(); ?>">
                            <img src="http://source.unsplash.com/random/300x200" alt="">
                        </a>
                    </div>
                    <div class="blog__item__content">
                        <a href="<?= $this->getBaseUrl().'blog/'.$post->getIdentifier(); ?>">
                            <h2 class="title blog__content__title"><?= $post->getTitle() ?></h2>
                        </a>
                        <a href="<?= $this->getBaseUrl().'blog/'.$post->getIdentifier(); ?>">
                            <?= $post->getShortContent() ?>
                        </a>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</section>
