<?php
$post = $this->getPost();
$cat = array_keys($post->getCats())[0];
?>
<section class="blog">
    <div class="blog__child" style="background-image: url(http://source.unsplash.com/random/)">
        <ul class="social">
            <li>
                <a href="https://www.instagram.com/silkaniparis/"><img src="<?= Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'instagram.png' ?>"
                                srcset="<?= Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'instagram@2x.png' ?> 2x"
                                alt=""></a>
            </li>
            <li>
                <a href="https://www.facebook.com/Silkani-697830700328676/"><img src="<?= Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'fb.png' ?>"
                                srcset="<?= Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'fb@2x.png' ?> 2x"
                                alt=""></a>
            </li>
        </ul>
    </div>
    <div class="blog__child">
        <div class="post__hero">
            <div class="post__hero__content">
                <h2 class="post__cat"><?= $cat ?></h2>
                <h1 class="post__title"><?= $post->getTitle() ?></h1>
                <h3 class="post__author">de Claudia carvalho</h3>
                <span class="post__date">
                    <?= Mage::app()->getLocale()->date($post->getCreatedTime(), 'Y-M-d')->toString('d MMMM Y'); ?>
                </span>
            </div>
            <span class="post__read-more">
                Découvrir l'article
            </span>
        </div>
        <div class="post__article">
            <?= $post->getPostContent() ?>
        </div>
    </div>
</section>
