<section class="category-section">
    <div class="category-wrapper">
      <h2 class="title-1">
          Collection Vivienne
      </h2>
      <div class="select-style">
          <select>
              <option value="Trier par Couleur">Trier par Couleur</option>
              <option value="Rouge">Rouge</option>
              <option value="Bleu">Bleu</option>
              <option value="Orange">Orange</option>
              <option value="Gris">Gris</option>
              <option value="Noir">Noir</option>
              <option value="Blanc">Blanc</option>
          </select>
      </div>
      <div class="search-bar">
        <input type="text" class="search" placeholder="Rechercher">
      </div>

      <div class="category-list">
        <ul class="category-items" >
          <li class="category-item">
            <div class="item-background">
              <div class="item-background-hover">
                <div class="block-size">
                  <h3 class="title-3">
                    Bleu Nuit
                  </h3>
                  <span class="price">
                    190 €
                  </span>
                  <h4 class="title-4">
                    tailles disponible
                  </h4>
                  <ul class="sizes">
                    <li class="size">
                      32
                    </li>
                    <li class="size">
                      34
                    </li>
                    <li class="size error">
                      36
                    </li>
                    <li class="size">
                      38
                    </li>
                    <li class="size error">
                      40
                    </li>
                    <li class="size">
                      42
                    </li>
                    <li class="size">
                      44
                    </li>
                  </ul>
                  <p class="confidence">
                    Soie fabriqué en France
                  </p>
                </div>
              </div>
            </div>
            <div class="item-price">
              <span class="color">
                Ivoire -
              </span>
              <span class="price">
                1000€
              </span>
            </div>
          </li>
          <li class="category-item">
            <div class="item-background">
              <div class="item-background-hover">
                <div class="block-size">
                  <h3 class="title-3">
                    Bleu Nuit
                  </h3>
                  <span class="price">
                    190 €
                  </span>
                  <h4 class="title-4">
                    tailles disponible
                  </h4>
                  <ul class="sizes">
                    <li class="size">
                      32
                    </li>
                    <li class="size">
                      34
                    </li>
                    <li class="size error">
                      36
                    </li>
                    <li class="size">
                      38
                    </li>
                    <li class="size error">
                      40
                    </li>
                    <li class="size">
                      42
                    </li>
                    <li class="size">
                      44
                    </li>
                  </ul>
                  <p class="confidence">
                    Soie fabriqué en France
                  </p>
                </div>
              </div>
            </div>
            <div class="item-price">
              <span class="color">
                Ivoire -
              </span>
              <span class="price">
                1000€
              </span>
            </div>
          </li>
          <li class="category-item">
            <div class="item-background">
              <div class="item-background-hover">
                <div class="block-size">
                  <h3 class="title-3">
                    Bleu Nuit
                  </h3>
                  <span class="price">
                    190 €
                  </span>
                  <h4 class="title-4">
                    tailles disponible
                  </h4>
                  <ul class="sizes">
                    <li class="size">
                      32
                    </li>
                    <li class="size">
                      34
                    </li>
                    <li class="size error">
                      36
                    </li>
                    <li class="size">
                      38
                    </li>
                    <li class="size error">
                      40
                    </li>
                    <li class="size">
                      42
                    </li>
                    <li class="size">
                      44
                    </li>
                  </ul>
                  <p class="confidence">
                    Soie fabriqué en France
                  </p>
                </div>
              </div>
            </div>
            <div class="item-price">
              <span class="color">
                Ivoire -
              </span>
              <span class="price">
                1000€
              </span>
            </div>
          </li>
          <li class="category-item">
            <div class="item-background">
              <div class="item-background-hover">
                <div class="block-size">
                  <h3 class="title-3">
                    Bleu Nuit
                  </h3>
                  <span class="price">
                    190 €
                  </span>
                  <h4 class="title-4">
                    tailles disponible
                  </h4>
                  <ul class="sizes">
                    <li class="size">
                      32
                    </li>
                    <li class="size">
                      34
                    </li>
                    <li class="size error">
                      36
                    </li>
                    <li class="size">
                      38
                    </li>
                    <li class="size error">
                      40
                    </li>
                    <li class="size">
                      42
                    </li>
                    <li class="size">
                      44
                    </li>
                  </ul>
                  <p class="confidence">
                    Soie fabriqué en France
                  </p>
                </div>
              </div>
            </div>
            <div class="item-price">
              <span class="color">
                Ivoire -
              </span>
              <span class="price">
                1000€
              </span>
            </div>
          </li>
          <li class="category-item">
            <div class="item-background">
              <div class="item-background-hover">
                <div class="block-size">
                  <h3 class="title-3">
                    Bleu Nuit
                  </h3>
                  <span class="price">
                    190 €
                  </span>
                  <h4 class="title-4">
                    tailles disponible
                  </h4>
                  <ul class="sizes">
                    <li class="size">
                      32
                    </li>
                    <li class="size">
                      34
                    </li>
                    <li class="size error">
                      36
                    </li>
                    <li class="size">
                      38
                    </li>
                    <li class="size error">
                      40
                    </li>
                    <li class="size">
                      42
                    </li>
                    <li class="size">
                      44
                    </li>
                  </ul>
                  <p class="confidence">
                    Soie fabriqué en France
                  </p>
                </div>
              </div>
            </div>
            <div class="item-price">
              <span class="color">
                Ivoire -
              </span>
              <span class="price">
                1000€
              </span>
            </div>
          </li>
          <li class="category-item">
            <div class="item-background">
              <div class="item-background-hover">
                <div class="block-size">
                  <h3 class="title-3">
                    Bleu Nuit
                  </h3>
                  <span class="price">
                    190 €
                  </span>
                  <h4 class="title-4">
                    tailles disponible
                  </h4>
                  <ul class="sizes">
                    <li class="size">
                      32
                    </li>
                    <li class="size">
                      34
                    </li>
                    <li class="size error">
                      36
                    </li>
                    <li class="size">
                      38
                    </li>
                    <li class="size error">
                      40
                    </li>
                    <li class="size">
                      42
                    </li>
                    <li class="size">
                      44
                    </li>
                  </ul>
                  <p class="confidence">
                    Soie fabriqué en France
                  </p>
                </div>
              </div>
            </div>
            <div class="item-price">
              <span class="color">
                Ivoire -
              </span>
              <span class="price">
                1000€
              </span>
            </div>
          </li>
          <li class="category-item">
            <div class="item-background">
              <div class="item-background-hover">
                <div class="block-size">
                  <h3 class="title-3">
                    Bleu Nuit
                  </h3>
                  <span class="price">
                    190 €
                  </span>
                  <h4 class="title-4">
                    tailles disponible
                  </h4>
                  <ul class="sizes">
                    <li class="size">
                      32
                    </li>
                    <li class="size">
                      34
                    </li>
                    <li class="size error">
                      36
                    </li>
                    <li class="size">
                      38
                    </li>
                    <li class="size error">
                      40
                    </li>
                    <li class="size">
                      42
                    </li>
                    <li class="size">
                      44
                    </li>
                  </ul>
                  <p class="confidence">
                    Soie fabriqué en France
                  </p>
                </div>
              </div>
            </div>
            <div class="item-price">
              <span class="color">
                Ivoire -
              </span>
              <span class="price">
                1000€
              </span>
            </div>
          </li>
          <li class="category-item">
            <div class="item-background">
              <div class="item-background-hover">
                <div class="block-size">
                  <h3 class="title-3">
                    Bleu Nuit
                  </h3>
                  <span class="price">
                    190 €
                  </span>
                  <h4 class="title-4">
                    tailles disponible
                  </h4>
                  <ul class="sizes">
                    <li class="size">
                      32
                    </li>
                    <li class="size">
                      34
                    </li>
                    <li class="size error">
                      36
                    </li>
                    <li class="size">
                      38
                    </li>
                    <li class="size error">
                      40
                    </li>
                    <li class="size">
                      42
                    </li>
                    <li class="size">
                      44
                    </li>
                  </ul>
                  <p class="confidence">
                    Soie fabriqué en France
                  </p>
                </div>
              </div>
            </div>
            <div class="item-price">
              <span class="color">
                Ivoire -
              </span>
              <span class="price">
                1000€
              </span>
            </div>
          </li>
          <li class="category-item">
            <div class="item-background">
              <div class="item-background-hover">
                <div class="block-size">
                  <h3 class="title-3">
                    Bleu Nuit
                  </h3>
                  <span class="price">
                    190 €
                  </span>
                  <h4 class="title-4">
                    tailles disponible
                  </h4>
                  <ul class="sizes">
                    <li class="size">
                      32
                    </li>
                    <li class="size">
                      34
                    </li>
                    <li class="size error">
                      36
                    </li>
                    <li class="size">
                      38
                    </li>
                    <li class="size error">
                      40
                    </li>
                    <li class="size">
                      42
                    </li>
                    <li class="size">
                      44
                    </li>
                  </ul>
                  <p class="confidence">
                    Soie fabriqué en France
                  </p>
                </div>
              </div>
            </div>
            <div class="item-price">
              <span class="color">
                Ivoire -
              </span>
              <span class="price">
                1000€
              </span>
            </div>
          </li>

        </ul>

      </div>
    </div>
</section>
